
// generate me fairy tale sentence, about "вставить имя или предмет"
// made a small story using this text (only simple words, for kids 3-5 years old) and no more than 10 words in a sentence. - 
// translate this to polish but using only simple words, because it's for 3-5 years old kids - 
// translate to russian exactly with the preservation of punctuation - 

// d01 - dialogs
// t01 - tale
// с01 - рожд
const TEXTS = {
	christmas01: [
"Bałwanek i Śnieżny Aniołek",
"Pewnego dnia mały bałwanek stał zupełnie sam.",
"Popatrzył w niebo i pomyślał życzenie.",
"„Chciałbym mieć przyjaciela,” szepnął bałwanek.",
"Niedaleko dziecko zrobiło na śniegu aniołka.",
"Nagle aniołek zaczął się ruszać!",
"„Cześć, Bałwanku! Jestem twoim nowym przyjacielem!” powiedział aniołek.",
"Bałwanek się uśmiechnął i poczuł się bardzo szczęśliwy.",
"Bawili się w śniegu każdego dnia.",
"Lepili śnieżki i budowali fortece razem.",
"Przytulenie aniołka ogrzało bałwanka.",
"Teraz mały bałwanek już nigdy nie był sam.",
"Miał przyjaciela, z którym dzielił radosne zimowe dni.",
"Снеговик и Снежный Ангел",
"Однажды маленький снеговик стоял совсем один.",
"Он посмотрел на небо и загадал желание.",
"«Я бы хотел иметь друга,» — прошептал снеговик.",
"Недалеко ребенок сделал на снегу ангела.",
"Вдруг ангел начал двигаться!",
"«Привет, Снеговик! Я твой новый друг!» — сказал ангел.",
"Снеговик улыбнулся и почувствовал себя очень счастливым.",
"Они играли в снегу каждый день.",
"Лепили снежки и строили крепости вместе.",
"Объятие ангела согрело снеговика.",
"Теперь маленький снеговик больше никогда не был один.",
"У него был друг, с которым он делил радостные зимние дни."
	],
	christmas02: [
'Życzenie Małego Bałwanka',
'Mały bałwanek stał sam na śnieżnym podwórku.',
'Chciał mieć przyjaciela do wspólnej zabawy.',
'Pewnego dnia dziecko zrobiło dużego śnieżnego aniołka.',
'Śnieżny aniołek ożył i się uśmiechnął!',
'„Cześć, mały bałwanku! Pobawmy się razem,” powiedział aniołek.',
'Ślizgali się po lodzie i tańczyli na śniegu.',
'Budowali małe śnieżne zamki i śmiali się cały dzień.',
'Mały bałwanek był bardzo szczęśliwy ze swoim przyjacielem.',
'Razem sprawiali, że zimowe dni były ciepłe i radosne.',
'Bałwanek i aniołek uśmiechali się pod migoczącymi gwiazdami.',
'Желание Маленького Снеговика',
'Маленький снеговик стоял один на снежном дворе.',
'Он хотел иметь друга для совместных игр.',
'Однажды ребёнок сделал большого снежного ангела.',
'Снежный ангел ожил и улыбнулся!',
'«Привет, маленький снеговик! Давай играть вместе,» – сказал ангел.',
'Они скользили по льду и танцевали на снегу.',
'Строили маленькие снежные замки и смеялись весь день.',
'Маленький снеговик был очень счастлив со своим другом.',
'Вместе они делали зимние дни тёплыми и радостными.',
'Снеговик и ангел улыбались под мерцающими звёздами.'
	],
	christmas03: [
'Zagubiony Miś',
'W wigilijną noc miś był całkiem sam.',
'Zgubił się i tęsknił za swoim najlepszym przyjacielem.',
'Miś szedł przez śnieg, szukając swojego domu.',
'W końcu zobaczył ciepłe światło w oknie.',
'Miś wspiął się i zapukał do drzwi.',
'Dziecko otworzyło drzwi i zobaczyło misia.',
'„Ojej! Wróciłeś!” – powiedziało dziecko, mocno go przytulając.',
'Miś miał kartkę: „Ja też za tobą tęskniłem!”',
'Znowu razem, uśmiechali się i bawili pod choinką.',
'Dziecko i miś byli szczęśliwi w wigilijną noc.',
'Потерянный Мишка',
'В рождественскую ночь мишка был совсем один.',
'Он потерялся и скучал по своему лучшему другу.',
'Мишка шёл через снег, ищя свой дом.',
'Наконец, он увидел тёплый свет в окне.',
'Мишка поднялся и постучал в дверь.',
'Ребёнок открыл дверь и увидел мишку.',
'«Ой! Ты вернулся!» – сказал ребёнок, крепко его обняв.',
'У мишки была записка: «Я тоже по тебе скучал!»',
'Снова вместе, они улыбались и играли под ёлкой.',
'Ребёнок и мишка были счастливы в рождественскую ночь.'
	],
	christmas04: [
"Magiczna Ozdoba",
"W małym miasteczku była magiczna ozdoba.",
"Spełniała jedno życzenie każdej rodziny w okolicy.",
"Jedna rodzina życzyła sobie ogrodu pełnego kwiatów.",
"Następnego ranka kolorowe kwiaty wyrosły w całym ogrodzie!",
"Inna rodzina życzyła sobie ciepłego jedzenia na stole.",
"Tego wieczoru pojawiła się pyszna uczta z wieloma daniami.",
"Mała dziewczynka chciała, by jej zaginiony kotek wrócił do domu.",
"Wkrótce usłyszała 'miau' i zobaczyła kotka przed domem!",
"Magiczna ozdoba przyniosła radość każdej rodzinie w pobliżu.",
"Wszyscy się uśmiechali, śmiali i dzielili radością z sąsiadami.",
"Miasteczko wypełniła miłość dzięki tej magii.",
"Волшебное Украшение",
"В маленьком городке было волшебное украшение.",
"Оно исполняло одно желание каждой семьи в округе.",
"Одна семья пожелала себе сад, полный цветов.",
"На следующее утро цветные цветы выросли по всему саду!",
"Другая семья пожелала себе тёплой еды на столе.",
"В тот вечер появилась вкусная трапеза с множеством блюд.",
"Маленькая девочка захотела, чтобы её потерявшийся котёнок вернулся домой.",
"Скоро она услышала 'мяу' и увидела котёнка перед домом!",
"Волшебное украшение принесло радость каждой семье рядом.",
"Все улыбались, смеялись и делились радостью с соседями.",
"Городок наполнился любовью благодаря этой магии."
	],
	christmas05: [
'Niewidzialne Prezenty',
'Na Biegunie Północnym elfy były zajęte pakowaniem prezentów.',
'Ale jeden elf znalazł rolkę dziwnego, błyszczącego papieru.',
'"Użyjmy tego!" powiedział, nie wiedząc, że jest niewidzialny!',
'Zapakowali wszystkie prezenty w niewidzialny papier.',
'"Gotowe! Skończone!" elfy cieszyły się ze swojej pracy.',
'W świąteczny poranek dzieci wszędzie otworzyły puste pudełka!',
'"Gdzie są prezenty?" zapytały dzieci, zdziwione i zmartwione.',
'Ale potem dotknęły i znalazły niewidzialne zabawki w środku!',
'Wszyscy się śmiali, gdy zrozumieli, że prezenty nie zniknęły.',
'To były wesołe i niezapomniane święta dla wszystkich dzieci!',
'Невидимые Подарки',
'На Северном Полюсе эльфы были заняты упаковкой подарков.',
'Но один эльф нашел рулон странной, блестящей бумаги.',
'"Давайте используем это!" — сказал он, не зная, что она невидимая!',
'Они упаковали все подарки в невидимую бумагу.',
'"Готово! Закончили!" — обрадовались эльфы своей работе.',
'В праздничное утро дети повсюду открыли пустые коробки!',
'"Где подарки?" — спросили дети, удивленные и обеспокоенные.',
'Но потом они потрогали и нашли невидимые игрушки внутри!',
'Все смеялись, когда поняли, что подарки не исчезли.',
'Это были веселые и незабываемые праздники для всех детей!'
	],
	christmas06: [
'Samotna Choinka',
'W cichym lesie stała mała, samotna choinka.',
'Nikt jej nie ozdobił, i było jej bardzo smutno.',
'"Chciałabym, żeby ktoś mnie pokochał," szepnęła mała choinka.',
'Pewnego dnia zwierzęta w lesie zobaczyły samotną choinkę.',
'"Zróbmy ją piękną na święta!" powiedziała wiewiórka.',
'Ptaki przyniosły jagody, a zające szyszki.',
'Jelenie dodały błyszczące liście i choinka zaczęła lśnić.',
'Wkrótce choinka była jasna od ozdób i wesołych światełek.',
'Zwierzęta zebrały się wokół i śpiewały radosne świąteczne piosenki.',
'Samotna choinka stała się sercem leśnej uroczystości.',
'Każda choinka zasługuje na miłość, i ta ją poczuła!',
'Одинокая Ёлочка',
'В тихом лесу стояла маленькая, одинокая ёлочка.',
'Никто её не украсил, и ей было очень грустно.',
'"Хотела бы я, чтобы кто-то меня полюбил," — прошептала маленькая ёлочка.',
'Однажды животные в лесу увидели одинокую ёлочку.',
'"Давайте сделаем её красивой к празднику!" — сказала белка.',
'Птицы принесли ягоды, а зайцы — шишки.',
'Олени добавили блестящие листья, и ёлочка начала сиять.',
'Скоро ёлочка засияла от украшений и весёлых огоньков.',
'Животные собрались вокруг и пели радостные праздничные песни.',
'Одинокая ёлочка стала сердцем лесного праздника.',
'Каждая ёлочка заслуживает любви, и эта её почувствовала!'
	],
	christmas07: [
'Magiczny List na Święta',
'Pewnego dnia Mia napisała list do Świętego Mikołaja.',
'Poprosiła Mikołaja, by pomógł smutnej rodzinie.',
'List Mii trafił przez pomyłkę do dobrej rodziny.',
'Rodzina przeczytała list i uśmiechnęła się szeroko.',
'„Będziemy pomocnikami Mikołaja!” powiedzieli z radością.',
'Potajemnie przynieśli jedzenie, zabawki i ciepłe koce.',
'Smutna rodzina znalazła prezenty pod drzwiami.',
'„Wow! Mikołaj nas znalazł!” krzyknął szczęśliwie mały chłopiec.',
'Mia nigdy nie wiedziała, że jej list uczynił święta tak wyjątkowymi.',
'Dobroć się rozprzestrzeniła i wszyscy poczuli magię miłości.',
'Магическое Письмо на Рождество',
'Однажды Мия написала письмо Святому Николаю.',
'Она попросила Николая помочь грустной семье.',
'Письмо Мии по ошибке попало к доброй семье.',
'Семья прочитала письмо и широко улыбнулась.',
'«Мы будем помощниками Николая!» — сказали они с радостью.',
'Они тайно принесли еду, игрушки и тёплые одеяла.',
'Грустная семья нашла подарки у двери.',
'«Вау! Николай нашёл нас!» — радостно воскликнул маленький мальчик.',
'Мия никогда не узнала, что её письмо сделало Рождество таким особенным.',
'Добро разошлось, и все почувствовали магию любви.'
	],
	christmas08: [
'Magiczna Kula Śnieżna',
'Pewnego dnia Max znalazł kulę śnieżną na biurku.',
'Kula śnieżna powiedziała: "Mam historię do opowiedzenia."',
'Max, zajęty człowiek, powiedział: "Nie mam czasu!"',
'Kula odpowiedziała: "Święta to więcej niż praca i prezenty."',
'Pokazała Maxowi dzieci, które śmiały się i dzieliły zabawkami.',
'Max zobaczył ludzi dających jedzenie przyjaciołom i obcym.',
'"Dlaczego oni dają?" zapytał Max kulę śnieżną.',
'"Dawanie daje radość," powiedziała kula ciepłym głosem.',
'Max się uśmiechnął i dał prezenty dzieciom i sąsiadom.',
'Teraz Max kochał święta, a dawanie czyniło go szczęśliwym.',
'Магический Снежный Шар',
'Однажды Макс нашёл снежный шар на столе.',
'Снежный шар сказал: "У меня есть история."',
'Макс, занятый человек, сказал: "У меня нет времени!"',
'Шар ответил: "Праздники — это больше, чем работа и подарки."',
'Он показал Максу детей, которые смеялись и делились игрушками.',
'Макс увидел людей, дающих еду друзьям и незнакомым.',
'"Почему они дают?" — спросил Макс снежный шар.',
'"Дарение приносит радость," — сказал шар тёплым голосом.',
'Макс улыбнулся и подарил подарки детям и соседям.',
'Теперь Макс любил праздники, а дарение делало его счастливым.'
	],
	christmas09: [
'Śmiejący się Renifer',
'Mikołaj miał nowego renifera o imieniu Chichotek.',
'Chichotek miał wyjątkowy dar: rozśmieszał wszystkich.',
'Kiedy sanie Mikołaja leciały, Chichotek opowiadał śmieszne żarty.',
'Elfy chichotały, a renifery śmiały się z radości.',
'Nawet Mikołaj śmiał się tak mocno, że brzuch mu drżał!',
'„Ho, ho, ho! To najlepsza przejażdżka saniami!”',
'Gwiazdki błyszczały, gdy śmiech wypełniał noc.',
'Dzieci na dole słyszały radość i uśmiechały się w łóżkach.',
'„Chichotku, czynisz święta jeszcze weselszymi!” – powiedział Mikołaj szczęśliwie.',
'Teraz w każde święta Chichotek roznosi śmiech po niebie.',
'Смеющийся Олень',
'У Миколая был новый олень по имени Хихотек.',
'Хихотек имел особый дар: он смешил всех.',
'Когда сани Миколая летели, Хихотек рассказывал смешные шутки.',
'Эльфы хихикали, а олени смеялись от радости.',
'Даже Миколай смеялся так сильно, что его живот дрожал!',
'«Хо, хо, хо! Это лучшая поездка на санях!»',
'Звёзды мерцали, пока смех наполнял ночь.',
'Дети внизу слышали радость и улыбались в кроватках.',
'«Хихотек, ты делаешь праздник ещё веселее!» – сказал Миколай счастливо.',
'Теперь каждое Рождество Хихотек разносит смех по небу.'
	],
	christmas10: [
'Magiczny Śnieg',
'Pewnej nocy na Święta z nieba padał śnieg.',
'Plac zabaw był pusty, cichy i bardzo spokojny.',
'Magiczne płatki śniegu błyszczały jak małe gwiazdki na ziemi.',
'Wkrótce plac zabaw stał się śnieżną, magiczną krainą.',
'Dzieci biegły, śmiały się i bawiły w śniegu.',
'Lepiły bałwany, robiły aniołki i ślizgały się na lodzie.',
'Rodzice dołączyli, rzucając śnieżkami i ciesząc się zabawą.',
'Śnieżny plac zabaw przyniósł wszystkim radość tej nocy.',
'Pod migoczącymi gwiazdami magia Świąt wypełniła ich serca.',
'Магический Снег',
'Однажды ночью на Рождество с неба падал снег.',
'Игровая площадка была пустой, тихой и очень спокойной.',
'Магические снежинки сияли, как маленькие звёздочки на земле.',
'Скоро площадка превратилась в снежную, волшебную страну.',
'Дети бежали, смеялись и играли в снегу.',
'Они лепили снеговиков, делали снежных ангелов и катались на льду.',
'Родители присоединились, бросая снежки и радуясь веселью.',
'Снежная площадка принесла всем радость в эту ночь.',
'Под мерцающими звёздами рождественская магия наполнила их сердца.'
	],
	christmas11: [
'Magiczne Kule Śnieżnego Bałwanka',
'Pewnego razu mały bałwanek kochał kule śnieżne.',
'„Chcę zebrać je wszystkie!” powiedział.',
'Pewnego dnia znalazł błyszczącą kulę śnieżną.',
'W środku śnieg wirował, a światełka świeciły.',
'„Wow! To jest takie magiczne,” powiedział bałwanek.',
'Zrobił półkę i postawił kulę na niej.',
'Co tydzień znajdował nową kulę śnieżną.',
'Niektóre miały drzewa, inne malutkie domki w środku.',
'Jego półka zmieniła się w świecącą, zimową wystawę.',
'Bałwanek uśmiechnął się. „Każda kula ma swoją historię!”',
'Kochał swoje kule i magię, którą przynosiły.',
'Marzenie bałwanka się spełniło.',
'Koniec.',
'Магические Шары Снежного Снеговика',
'Однажды маленький снеговик любил снежные шары.',
'«Хочу собрать их все!» — сказал он.',
'Однажды он нашел блестящий снежный шар.',
'Внутри снег кружился, а огоньки сияли.',
'«Вау! Это так магично», — сказал снеговик.',
'Он сделал полку и поставил шар на нее.',
'Каждую неделю он находил новый снежный шар.',
'В одних были деревья, в других — маленькие домики.',
'Его полка превратилась в сверкающую зимнюю выставку.',
'Снеговик улыбнулся. «У каждого шара своя история!»',
'Он любил свои шары и магию, которую они приносили.',
'Мечта снеговика сбылась.',
'Конец.'
	],
	christmas12: [
'Magiczna Laska Cukrowa',
'Pewnego dnia była magiczna laska cukrowa.',
'Mogła spełniać życzenia, słodkie i prawdziwe.',
'Pewnego zimnego dnia rodzina była bardzo smutna.',
'Nie mieli prezentów ani smakołyków na święta.',
'Dziewczynka znalazła laskę cukrową na ziemi.',
'Wzięła ją i cicho wypowiedziała życzenie.',
'„Proszę, przynieś radość mojej rodzinie,” powiedziała.',
'Laska cukrowa zaświeciła jasnym, ciepłym światłem.',
'Wkrótce dom wypełnił się śmiechem i radością.',
'Były prezenty, słodycze i dużo uścisków.',
'Rodzina uśmiechnęła się i podziękowała lasce cukrowej.',
'Przyniosła im miłość i magię do domu.',
'Волшебная Карамельная Трость',
'Однажды была волшебная карамельная трость.',
'Она могла исполнять желания, сладкие и настоящие.',
'В один холодный день семья была очень грустной.',
'У них не было подарков и угощений на праздник.',
'Девочка нашла карамельную трость на земле.',
'Она взяла её и тихо загадала желание.',
'«Пожалуйста, принеси радость моей семье», — сказала она.',
'Карамельная трость засияла ярким, тёплым светом.',
'Скоро дом наполнился смехом и радостью.',
'Были подарки, сладости и много объятий.',
'Семья улыбнулась и поблагодарила карамельную трость.',
'Она принесла им любовь и волшебство в дом.'
	],
	christmas13: [
'Mówiący Dziadek do Orzechów',
'W małej wiosce była nieśmiała dziewczynka.',
'Pewnego dnia znalazła mówiącego dziadka do orzechów.',
'Dziadek do orzechów powiedział: "Mogę pomóc ci mówić."',
'Dziewczynka szepnęła: "Naprawdę? Boję się spróbować."',
'"Uwierz w siebie," powiedział dziadek do orzechów łagodnie.',
'Zbliżały się święta, ale dziewczynka się bała.',
'"Poćwiczmy razem," powiedział dziadek do orzechów z uśmiechem.',
'Śpiewali, tańczyli, a dziewczynka stała się odważna.',
'Na przedstawieniu stanęła prosto i śpiewała głośno.',
'Wszyscy klaskali! Nieśmiała dziewczynka w końcu znalazła swój głos.',
'Говорящий Щелкунчик',
'В маленькой деревне жила застенчивая девочка.',
'Однажды она нашла говорящего щелкунчика.',
'Щелкунчик сказал: "Я могу помочь тебе говорить."',
'Девочка прошептала: "Правда? Я боюсь попробовать."',
'"Поверь в себя," мягко сказал щелкунчик.',
'Приближались праздники, но девочка боялась.',
'"Давай потренируемся вместе," сказал щелкунчик с улыбкой.',
'Они пели, танцевали, и девочка стала смелой.',
'На представлении она встала прямо и пела громко.',
'Все аплодировали! Застенчивая девочка наконец нашла свой голос.'
	],
	christmas14: [
'Wielka Noc Światełek',
'Świąteczne światełka były smutne.',
'„Nikt nas nie widzi” – mówiły.',
'Chciały, żeby ktoś je zauważył.',
'Więc zaczęły świecić bardzo jasno.',
'„Patrzcie! Światełka migoczą!” – krzyknęły dzieci.',
'Sąsiedzi wyszli, żeby zobaczyć blask.',
'„Wow! Jakie piękne!” – mówili wszyscy.',
'Światełka poczuły się radosne i ciepłe.',
'Teraz wszyscy kochali ich wesoły blask.',
'Cała okolica była pełna radości!',
'Великая Ночь Огоньков',
'Праздничные огоньки были грустны.',
'«Никто нас не видит», – говорили они.',
'Они хотели, чтобы кто-то их заметил.',
'Поэтому они начали светить очень ярко.',
'«Смотрите! Огоньки сверкают!» – закричали дети.',
'Соседи вышли, чтобы увидеть сияние.',
'«Вау! Какие красивые!» – говорили все.',
'Огоньки почувствовали себя радостными и теплыми.',
'Теперь все любили их весёлый свет.',
'Вся окрестность была полна радости!'
	],
	christmas15: [
'Był świąteczny poranek.',
'Kotek był zagubiony i zmarznięty.',
'Kotek zobaczył czerwony skarpetkę.',
'Wszedł do środka, żeby się ogrzać.',
'Dziecko znalazło kotka i uśmiechnęło się.',
'„Jesteś moim świątecznym prezentem!” – powiedziało.',
'Kotek zamruczał radośnie.',
'Dziecko i kotek zostali najlepszymi przyjaciółmi.',
'Święta były pełne radości i miłości!',
'Было рождественское утро.',
'Котёнок был потерян и замёрз.',
'Котёнок увидел красный носок.',
'Он залез внутрь, чтобы согреться.',
'Ребёнок нашёл котёнка и улыбнулся.',
'«Ты мой рождественский подарок!» – сказал(а) он(а).',
'Котёнок радостно замурлыкал.',
'Ребёнок и котёнок стали лучшими друзьями.',
'Рождество было полным радости и любви!',
	],
	christmas16: [
'Psotne Pierniczki',
'Pewnej nocy pierniczki się obudziły.',
'"Chcemy zwiedzać kuchnię!" szepnęły.',
'Zeszły z dużego słoika na ciastka.',
'"Zobaczmy miskę z cukrem!" powiedział jeden.',
'Pierniczki wskoczyły do miski z cukrem.',
'"Wow, takie słodkie i błyszczące!" śmiały się.',
'Potem ślizgały się po błyszczącym blacie.',
'"Popatrz na dzbanek z mlekiem!" powiedział inny pierniczek.',
'Spróbowały wspiąć się na dzbanek.',
'Ale o nie! Poślizgnęły się i spadły!',
'Mąka poleciała wszędzie! Pierniczki śmiały się i bawiły.',
'"To najlepsza przygoda!" krzyczały.',
'Kiedy nastał ranek, pierniczki wróciły.',
'"Zwiedzimy znowu jutro!" szepnęły radośnie.',
'Озорные Прянички',
'Однажды ночью прянички проснулись.',
'"Мы хотим исследовать кухню!" – прошептали они.',
'Они слезли с большой банки для печенья.',
'"Давайте посмотрим миску с сахаром!" – сказал один.',
'Прянички прыгнули в миску с сахаром.',
'"Вау, такие сладкие и блестящие!" – смеялись они.',
'Потом они скользили по блестящей столешнице.',
'"Посмотри на кувшин с молоком!" – сказал другой пряничек.',
'Они попытались взобраться на кувшин.',
'Но, о нет! Они поскользнулись и упали!',
'Мука разлетелась повсюду! Прянички смеялись и играли.',
'"Это лучшее приключение!" – закричали они.',
'Когда настало утро, прянички вернулись.',
'"Мы снова всё исследуем завтра!" – радостно прошептали они.'
	],
	christmas17: [
'Pomocnikiem był elf.',
'Ten elf lubił używać gadżetów.',
'„Zróbmy prezenty szybciej!” powiedział elf.',
'Elf zrobił specjalną maszynę.',
'Maszyna układała prezenty szybko i ładnie.',
'„Teraz wszystkie dzieci dostaną prezenty na czas!” powiedział Mikołaj.',
'Wszyscy krzyknęli: „Hurra dla elfa technika!”',
'Biegun Północny był znowu wesoły.',
'Święta były radosne dla wszystkich!',
'Помощником был эльф.',
'Этот эльф любил использовать гаджеты.',
'«Сделаем подарки быстрее!» — сказал эльф.',
'Эльф сделал специальную машину.',
'Машина складывала подарки быстро и аккуратно.',
'«Теперь все дети получат подарки вовремя!» — сказал Миколай.',
'Все закричали: «Ура для техника - эльфа!»',
'Северный полюс снова был веселым.',
'Праздники были радостными для всех!'
	],
	christmas18: [
'Dziecko zrobiło aniołka na śniegu.',
'Śnieżny aniołek ożył!',
'Uśmiechnął się i rozsypał magiczne płatki śniegu.',
'Płatki śniegu błyszczały w zimnym powietrzu.',
'„Pomyśl życzenie o dobroci!” powiedział aniołek.',
'Dziecko życzyło, aby wszyscy byli szczęśliwi.',
'Magiczne płatki spełniły to życzenie.',
'Ludzie wszędzie czuli miłość i radość.',
'„Dziękuję, śnieżny aniołku!” powiedziało dziecko.',
'Świat był pełen spokoju i uśmiechów.',
'Ребёнок сделал ангела на снегу.',
'Снежный ангел ожил!',
'Он улыбнулся и рассыпал волшебные снежинки.',
'Снежинки блестели в холодном воздухе.',
'«Загадай желание о доброте!» — сказал ангел.',
'Ребёнок пожелал, чтобы все были счастливы.',
'Волшебные снежинки исполнили это желание.',
'Люди повсюду чувствовали любовь и радость.',
'«Спасибо, снежный ангел!» — сказал ребёнок.',
'Мир был полон покоя и улыбок.'
	],
	christmas19: [
'Parada Małego Bębniarza',
'Mały bębniarz bardzo lubił grać na swoim bębnie.',
'Chciał dać radość wszystkim, których znał.',
'„Zrobię paradę!” – powiedział chłopiec z radością.',
'Poprosił swoich przyjaciół, by bawili się z nim.',
'„Pójdziemy i zagramy piosenki dla miasta!”',
'Dzieci przyniosły dzwonki, gwizdki i kolorowe flagi.',
'Parada szła ulicą z wesołą muzyką.',
'Sąsiedzi klaskali, uśmiechali się i dołączali do zabawy.',
'Bębenek chłopca połączył wszystkich tego dnia.',
'„Świąteczna radość jest najlepsza, gdy się nią dzielimy!” – powiedział.',
'Парад Маленького Барабанщика',
'Маленький барабанщик очень любил играть на своём барабане.',
'Он хотел подарить радость всем, кого знал.',
'«Я устрою парад!» – радостно сказал мальчик.',
'Он попросил своих друзей повеселиться с ним.',
'«Мы пойдём и сыграем песни для города!»',
'Дети принесли колокольчики, свистки и разноцветные флаги.',
'Парад шёл по улице с весёлой музыкой.',
'Соседи хлопали, улыбались и присоединялись к празднику.',
'Барабан мальчика объединил всех в тот день.',
'«Праздничная радость лучше, когда мы ею делимся!» – сказал он.'
	],
	christmas20: [
'Samotna Choinka',
'W kącie stała samotna choinka.',
'Choinka była smutna i bardzo samotna.',
'Pewnego dnia błyszczące ozdoby powiedziały: „Zostańmy przyjaciółmi!”',
'Migoczące światełka dołączyły i powiedziały: „Będziemy świecić z tobą!”',
'Razem śmiały się, tańczyły i świetnie się bawiły.',
'Pokój zrobił się jasny, wesoły i pełen radości.',
'Teraz choinka już nie była samotna, tylko bardzo kochana.',
'Одинокая Ёлочка',
'В углу стояла одинокая ёлочка.',
'Ёлочка была грустная и очень одинокая.',
'Однажды блестящие игрушки сказали: «Давайте будем друзьями!»',
'Мигающие огоньки присоединились и сказали: «Мы будем светиться с тобой!»',
'Вместе они смеялись, танцевали и прекрасно веселились.',
'Комната стала яркой, весёлой и полной радости.',
'Теперь ёлочка больше не была одинокой, а очень любимой.'
	],
	christmas21: [
'Richard i Świąteczne Skarpetki',
'Richard miał małe, czerwone skarpetki.',
'"To są moje świąteczne skarpetki!" powiedział radośnie.',
'Skarpetki były miękkie i ciepłe.',
'Richard biegał po domu, wesoło się śmiejąc.',
'Nagle skarpetka zniknęła!',
'"Moja skarpetka!" zawołał Richard zmartwiony.',
'Szukał pod stołem, ale jej tam nie było.',
'Szukał za sofą, ale dalej nic.',
'"Richard, zobacz tutaj!" zawołał tata.',
'Skarpetka była na głowie psa!',
'"Piesek ukradł moją skarpetkę!" śmiał się Richard.',
'Wszyscy się śmiali razem z nim.',
'Richard założył obie skarpetki i przytulił psa.',
'"Teraz jest prawdziwa świąteczna radość!" powiedział szczęśliwie.',
'Ричард и Рождественские Носочки',
'Ричард имел маленькие, красные носочки.',
'"Это мои рождественские носочки!" – радостно сказал он.',
'Носочки были мягкие и теплые.',
'Ричард бегал по дому, весело смеясь.',
'Вдруг носочек исчез!',
'"Мой носочек!" – воскликнул обеспокоенный Ричард.',
'Он искал под столом, но там его не было.',
'Он искал за диваном, но всё равно ничего.',
'"Ричард, посмотри сюда!" – крикнул папа.',
'Носочек был на голове у собаки!',
'"Собачка украла мой носочек!" – смеялся Ричард.',
'Все смеялись вместе с ним.',
'Ричард надел оба носочка и обнял собаку.',
'"Теперь это настоящая рождественская радость!" – счастливо сказал он.'
	],
	christmas22: [
"Nowy Przyjaciel Bałwanka",
"Pewnego zimowego dnia mały bałwanek stał całkiem sam.",
"Spojrzał w niebo i pomyślał życzenie.",
"„Chcę mieć przyjaciela,” szepnął cicho bałwanek.",
"Niedaleko dziecko zrobiło dużego, pięknego aniołka ze śniegu.",
"Aniołek ze śniegu zabłyszczał i zaczął się ruszać!",
"Otworzył ramiona i uśmiechnął się jasno.",
"„Będę twoim przyjacielem!” powiedział z radością.",
"Bałwanek i aniołek bawili się razem w śniegu.",
"Lepili śnieżki i tańczyli w zimowym świetle.",
"Codziennie śmiali się i bawili wesoło.",
"Bałwanek już nie był sam.",
"Jego życzenie się spełniło—przyjaciel na zimowe dni!",
"Новый Друг Снеговика",
"Однажды зимним днем маленький снеговик стоял совсем один.",
"Он посмотрел на небо и загадал желание.",
"«Я хочу друга,» тихо прошептал снеговик.",
"Недалеко ребенок сделал большого, красивого снежного ангела.",
"Снежный ангел засверкал и начал двигаться!",
"Он раскрыл руки и ярко улыбнулся.",
"«Я буду твоим другом!» сказал он с радостью.",
"Снеговик и ангел играли вместе в снегу.",
"Они лепили снежки и танцевали в зимнем свете.",
"Каждый день они смеялись и весело играли.",
"Снеговик больше не был один.",
"Его желание сбылось — друг на зимние дни!"
	],
	christmas23: [
'Dobry Piekarz i Wielka Niespodzianka Świętego Mikołaja',
'W małym miasteczku mieszkał dobry piekarz.',
'Pewnej zimnej nocy usłyszał hałas na dachu.',
'"Kto to może być?" pomyślał głośno piekarz.',
'Spojrzał w górę i zobaczył buty w kominie!',
'"O nie! Ktoś utknął!" powiedział piekarz.',
'Wszedł na górę i zobaczył Świętego Mikołaja w kominie.',
'"Mikołaju! Utknąłeś! Nie martw się, pomogę!" powiedział.',
'Piekarz ciągnął i szarpał z całej siły.',
'Jednym wielkim szarpnięciem wyciągnął Mikołaja!',
'"Dziękuję, dobry piekarzu! Uratowałeś święta!" ucieszył się Mikołaj.',
'Mikołaj był tak szczęśliwy, że przytulił piekarza.',
'"Świętujmy to z ciastkami i śmiechem!" powiedział Mikołaj.',
'Piekarz upiekł ciepłe ciastka dla siebie i Mikołaja.',
'Jedli ciastka i śmiali się przy ciepłym ogniu.',
'Miasteczko spało, ale piekarnia była pełna światła.',
'I tak dobry piekarz uratował świąteczną noc!',
'Добрый Пекарь и Большой Сюрприз Святого Николая',
'В маленьком городке жил добрый пекарь.',
'Одной холодной ночью он услышал шум на крыше.',
'"Кто это может быть?" — подумал вслух пекарь.',
'Он посмотрел вверх и увидел ботинки в дымоходе!',
'"О нет! Кто-то застрял!" — сказал пекарь.',
'Он залез наверх и увидел Святого Николая в дымоходе.',
'"Николай! Ты застрял! Не волнуйся, я помогу!" — сказал он.',
'Пекарь тянул и дергал изо всех сил.',
'Одним большим рывком он вытащил Николая!',
'"Спасибо, добрый пекарь! Ты спас Рождество!" — обрадовался Николай.',
'Николай был так счастлив, что обнял пекаря.',
'"Давай отпразднуем это с печеньем и смехом!" — сказал Николай.',
'Пекарь испек теплое печенье для себя и Николая.',
'Они ели печенье и смеялись у теплого огня.',
'Город спал, но пекарня светилась.',
'И так добрый пекарь спас рождественскую ночь!'
	],
	christmas24: [
'Zagubiony Miś Wraca do Domu',
'Była Wigilia, a dziecko było smutne.',
'Ich miś zaginął i nigdzie go nie było.',
'"Tęsknię za moim misiem," szepnęło cicho dziecko.',
'Na dworze śnieg cicho padał na ziemię.',
'Nagle ktoś zapukał do drzwi wejściowych.',
'Dziecko pobiegło i otworzyło z uśmiechem.',
'Na schodach był zaginiony miś!',
'Do łapki misia przyczepiona była mała karteczka.',
'"Ja też za tobą tęskniłem!" mówiła karteczka.',
'Dziecko przytuliło misia mocno ze łzami radości.',
'Teraz święta były idealne, bo miś wrócił do domu.',
'Потерянный Мишка Возвращается Домой',
'Была Канун Рождества, а ребёнок был грустный.',
'Их мишка потерялся и нигде его не было.',
'"Я скучаю по своему мишке," тихо прошептал ребёнок.',
'На улице снег тихо падал на землю.',
'Вдруг кто-то постучал в входную дверь.',
'Ребёнок побежал и открыл с улыбкой.',
'На ступеньках был потерянный мишка!',
'К лапке мишки была прикреплена маленькая записка.',
'"Я тоже по тебе скучал!" — говорила записка.',
'Ребёнок крепко обнял мишку со слезами радости.',
'Теперь праздник был идеальным, потому что мишка вернулся домой.'
	],
	christmas25: [
'Loli, Wróżka Śnieżynka',
'Loli była malutką wróżką śnieżynką z błyszczącymi skrzydłami.',
'Mieszkała w chmurach wysoko nad śnieżną ziemią.',
'Pewnej zimnej nocy leśne zwierzątka drżały z zimna.',
'"Zima jest za mroźna!" powiedział smutno mały króliczek.',
'Loli zobaczyła je i chciała pomóc swoją magią.',
'Machnęła swoją różdżką, i małe gwiazdki rozświetliły niebo.',
'Mroźne powietrze zrobiło się ciepłe i lśniło delikatnym światłem.',
'Zwierzątka poczuły ciepło i tańczyły pod migoczącym niebem.',
'"Dziękujemy, Loli! Sprawiłaś, że noc jest ciepła i jasna!"',
'Loli uśmiechnęła się i poleciała dalej, niosąc radość wszędzie.',
'Лоли, Фея Снежинка',
'Лоли была маленькой феей снежинкой с блестящими крыльями.',
'Она жила в облаках высоко над снежной землёй.',
'Однажды холодной ночью лесные зверята дрожали от холода.',
'"Зима слишком морозная!" — грустно сказал маленький кролик.',
'Лоли увидела их и захотела помочь своей магией.',
'Она взмахнула своей палочкой, и маленькие звёздочки осветили небо.',
'Морозный воздух стал тёплым и засверкал мягким светом.',
'Зверята почувствовали тепло и танцевали под мерцающим небом.',
'"Спасибо, Лоли! Ты сделала ночь тёплой и светлой!"',
'Лоли улыбнулась и полетела дальше, принося радость повсюду.'
	],
	christmas26: [
'Gwiaździsta Podróż Mikołaja',
'Mikołaj leciał wysoko z reniferami po niebie.',
'Gwiazdy świeciły jasno, rozświetlając ciemną noc.',
'Magiczna gwiazda pokazywała drogę do każdego domu.',
'Mikołaj przynosił prezenty i uśmiechy wszystkim dzieciom.',
'Renifery biegły szybko po śnieżnych dachach.',
'„Ho, ho, ho!” – mówił Mikołaj radosny i szczęśliwy.',
'Dzieci spały, śniąc o niespodziankach i zabawie.',
'Magiczna gwiazda prowadziła Mikołaja przez cichą noc.',
'„Dobra robota, renifery!” – powiedział Mikołaj, gdy sanie stanęły.',
'Ranek nadszedł, a dzieci śmiały się z radości!',
'Звёздное путешествие Николая',
'Николай летел высоко с оленями по небу.',
'Звёзды ярко сияли, освещая тёмную ночь.',
'Волшебная звезда указывала путь к каждому дому.',
'Николай приносил подарки и улыбки всем детям.',
'Олени быстро бежали по заснеженным крышам.',
'«Хо-хо-хо!» – говорил Николай радостный и счастливый.',
'Дети спали, мечтая о сюрпризах и играх.',
'Волшебная звезда вела Николая через тихую ночь.',
'«Хорошая работа, олени!» – сказал Николай, когда сани остановились.',
'Наступило утро, и дети смеялись от радости!'
	]
};